# GET http://localhost:8080/pet/all HTTP/1.1

# PUT http://localhost:8080/pet/update/1 HTTP/1.1
# Content-Type: application/json

# {
#     "petName" : "Kiisumiisu",
#     "code":"112233445566",
#     "petType" : "Cat",
#     "furColor" : "Black",
#     "country" : "Poland"
# }
# DELETE http://localhost:8080/pet/delete/1
